<?php if (!defined('BASEPATH')) exit('No direct script access allowed');

require_once(APPPATH . 'third_party/tcpdf/tcpdf.php');

class Tcpdf_custom extends TCPDF
{
	// HEADER OTOMATIS SETIAP HALAMAN
	public function Header()
	{
		$hal        = $this->getAliasNumPage();
		$total_hal  = $this->getAliasNbPages();
		$this->SetY(3);
		$header = '
            <table width="100%" cellpadding="0">
                <tr>
                    <td style="text-align:left; font-size:7px;">
                        <b>BMP - CIKOKOL</b>
                    </td>
                    <td style="text-align:right; font-size:7px;">
                        ' . date("Y-m-d") . ' | PAGE : ' . $hal . ' / ' . $total_hal . '
                    </td>
                </tr>
            </table>
            <h5 style="text-align:center; margin:0;">DUMMY ACCOUNT SUBLEDGER OVERVIEW</h5>
            <h6 style="text-align:center; margin-top: 10px;">PERIOD: JANUARY 2025</h6>
            <br>

        ';
		$this->writeHTML($header, false, false, false, false, '');

		// ============================
		// HEADER TABEL
		// ============================
		$tableHeader = '
		<table width="100%" cellpadding="3" style="font-size:7px;">
			<hr>
                <tr style="font-weight:bold; border-bottom:1px solid #000;">
                    <td width="8%">DATE</td>
                    <td width="14%">BATCH REFERENCE</td>
                    <td width="10%">VOUCHER NO</td>
                    <td width="32%">JOURNAL DESCRIPTION</td>
                    <td width="12%" align="right">DEBIT</td>
                    <td width="12%" align="right">CREDIT</td>
                    <td width="12%" align="right">BALANCE</td>
                </tr>
			<hr>
        </table>
        ';
		$this->writeHTML($tableHeader, false, false, false, false, '');
	}

	// FOOTER OTOMATIS
	public function Footer()
	{
		$this->SetY(-12);

		$footer = '
            <table width="100%" cellpadding="2" style="font-size:7px;">
                <tr>
                    <td style="text-align:center; color:#555;">© '.date('Y').' Lingga -  Generated by System</td>
                </tr>
            </table>
        ';

		$this->writeHTML($footer, false, false, false, false, '');
	}
}
